# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
variables:
- group: 'Secrets'
- group: 'Subscription'
steps:
- task: JamiePhillips.Terraform.TerraformTool.TerraformTool@0
  displayName: 'Use Terraform $(terraform.version)'
  inputs:
    version: '$(terraform.version)'
- script: |
   az login --service-principal -u $(tfsp-id) -p $(tfsp-secret) --tenant $(tenant_id)
   ACCESS_KEY=`az storage account keys list -n $(storage_acct) -o json | jq -r '.[0].value'`
   echo "##vso[task.setvariable variable=ACCESS_KEY]$ACCESS_KEY"
  displayName: 'AZ Login and Set ACCESS_KEY'
- script: |
   cat << EOT >> terraform.tfvars
   access_key = "$(ACCESS_KEY)"
   tenant_id = "$(tenant_id)"
   subscription_id = "$(subscription_id)"
   client_id = "$(tfsp-id)"
   client_secret = "$(tfsp-secret)"
   EOT
  workingDirectory: '$(terraform.path)'
  displayName: 'Create terraform.tfvars'
- script: |
   terraform init
  displayName: 'Terraform Init'
- script: |
   terraform validate
  workingDirectory: '$(terraform.path)'
  displayName: 'Terraform Validate'
- script: |
   terraform init -backend-config=resource_group_name=$(resource_group) -backend-config=storage_account_name=$(storage_acct) -backend-config=container_name=state -backend-config=key=$(state.key) -backend-config=access_key=$(ACCESS_KEY) -no-color -input=false
   terraform plan -out=tfplan -no-color -input=false
  displayName: 'Terraform Plan'
  workingDirectory: '$(System.DefaultWorkingDirectory)'